export default {
    "CityName": {
        "Aevum": "Aevum",
        "Chongqing": "Chongqing",
        "Ishima": "Ishima",
        "NewTokyo": "New Tokyo",
        "Sector12": "Sector-12",
        "Volhaven": "Volhaven",
    },
    "CodingContractName": {
        "AlgorithmicStockTraderI": "Algorithmic Stock Trader I",
        "AlgorithmicStockTraderII": "Algorithmic Stock Trader II",
        "AlgorithmicStockTraderIII": "Algorithmic Stock Trader III",
        "AlgorithmicStockTraderIV": "Algorithmic Stock Trader IV",
        "ArrayJumpingGame": "Array Jumping Game",
        "ArrayJumpingGameII": "Array Jumping Game II",
        "CompressionIIILZCompression": "Compression III: LZ Compression",
        "CompressionIILZDecompression": "Compression II: LZ Decompression",
        "CompressionIRLECompression": "Compression I: RLE Compression",
        "EncryptionICaesarCipher": "Encryption I: Caesar Cipher",
        "EncryptionIIVigenereCipher": "Encryption II: Vigenère Cipher",
        "FindAllValidMathExpressions": "Find All Valid Math Expressions",
        "FindLargestPrimeFactor": "Find Largest Prime Factor",
        "GenerateIPAddresses": "Generate IP Addresses",
        "HammingCodesEncodedBinaryToInteger": "HammingCodes: Encoded Binary to Integer",
        "HammingCodesIntegerToEncodedBinary": "HammingCodes: Integer to Encoded Binary",
        "MergeOverlappingIntervals": "Merge Overlapping Intervals",
        "MinimumPathSumInATriangle": "Minimum Path Sum in a Triangle",
        "Proper2ColoringOfAGraph": "Proper 2-Coloring of a Graph",
        "SanitizeParenthesesInExpression": "Sanitize Parentheses in Expression",
        "ShortestPathInAGrid": "Shortest Path in a Grid",
        "SpiralizeMatrix": "Spiralize Matrix",
        "SquareRoot": "Square Root",
        "SubarrayWithMaximumSum": "Subarray with Maximum Sum",
        "TotalWaysToSum": "Total Ways to Sum",
        "TotalWaysToSumII": "Total Ways to Sum II",
        "UniquePathsInAGridI": "Unique Paths in a Grid I",
        "UniquePathsInAGridII": "Unique Paths in a Grid II",
    },
    "CompanyName": {
        "AeroCorp": "AeroCorp",
        "AlphaEnterprises": "Alpha Enterprises",
        "BachmanAndAssociates": "Bachman & Associates",
        "BladeIndustries": "Blade Industries",
        "CIA": "Central Intelligence Agency",
        "CarmichaelSecurity": "Carmichael Security",
        "ClarkeIncorporated": "Clarke Incorporated",
        "CompuTek": "CompuTek",
        "DefComm": "DefComm",
        "DeltaOne": "DeltaOne",
        "ECorp": "ECorp",
        "FoodNStuff": "FoodNStuff",
        "FourSigma": "Four Sigma",
        "FulcrumTechnologies": "Fulcrum Technologies",
        "GalacticCybersystems": "Galactic Cybersystems",
        "GlobalPharmaceuticals": "Global Pharmaceuticals",
        "HeliosLabs": "Helios Labs",
        "IcarusMicrosystems": "Icarus Microsystems",
        "JoesGuns": "Joe's Guns",
        "KuaiGongInternational": "KuaiGong International",
        "LexoCorp": "LexoCorp",
        "MegaCorp": "MegaCorp",
        "NSA": "National Security Agency",
        "NWO": "NWO",
        "NetLinkTechnologies": "NetLink Technologies",
        "NoodleBar": "Noodle Bar",
        "NovaMedical": "Nova Medical",
        "OmegaSoftware": "Omega Software",
        "OmniTekIncorporated": "OmniTek Incorporated",
        "OmniaCybersystems": "Omnia Cybersystems",
        "Police": "Aevum Police Headquarters",
        "RhoConstruction": "Rho Construction",
        "SolarisSpaceSystems": "Solaris Space Systems",
        "StormTechnologies": "Storm Technologies",
        "SysCoreSecurities": "SysCore Securities",
        "UniversalEnergy": "Universal Energy",
        "VitaLife": "VitaLife",
        "WatchdogSecurity": "Watchdog Security",
    },
    "CrimeType": {
        "assassination": "Assassination",
        "bondForgery": "Bond Forgery",
        "dealDrugs": "Deal Drugs",
        "grandTheftAuto": "Grand Theft Auto",
        "heist": "Heist",
        "homicide": "Homicide",
        "kidnap": "Kidnap",
        "larceny": "Larceny",
        "mug": "Mug",
        "robStore": "Rob Store",
        "shoplift": "Shoplift",
        "traffickArms": "Traffick Arms",
    },
    "FactionName": {
        "Aevum": "Aevum",
        "BachmanAssociates": "Bachman & Associates",
        "BitRunners": "BitRunners",
        "BladeIndustries": "Blade Industries",
        "Bladeburners": "Bladeburners",
        "Chongqing": "Chongqing",
        "ChurchOfTheMachineGod": "Church of the Machine God",
        "ClarkeIncorporated": "Clarke Incorporated",
        "CyberSec": "CyberSec",
        "Daedalus": "Daedalus",
        "ECorp": "ECorp",
        "FourSigma": "Four Sigma",
        "FulcrumSecretTechnologies": "Fulcrum Secret Technologies",
        "Illuminati": "Illuminati",
        "Ishima": "Ishima",
        "KuaiGongInternational": "KuaiGong International",
        "MegaCorp": "MegaCorp",
        "NWO": "NWO",
        "Netburners": "Netburners",
        "NewTokyo": "New Tokyo",
        "NiteSec": "NiteSec",
        "OmniTekIncorporated": "OmniTek Incorporated",
        "Sector12": "Sector-12",
        "ShadowsOfAnarchy": "Shadows of Anarchy",
        "Silhouette": "Silhouette",
        "SlumSnakes": "Slum Snakes",
        "SpeakersForTheDead": "Speakers for the Dead",
        "Tetrads": "Tetrads",
        "TheBlackHand": "The Black Hand",
        "TheCovenant": "The Covenant",
        "TheDarkArmy": "The Dark Army",
        "TheSyndicate": "The Syndicate",
        "TianDiHui": "Tian Di Hui",
        "Volhaven": "Volhaven",
    },
    "FactionWorkType": {
        "field": "field",
        "hacking": "hacking",
        "security": "security",
    },
    "GymType": {
        "agility": "agi",
        "defense": "def",
        "dexterity": "dex",
        "strength": "str",
    },
    "JobField": {
        "software": "Software",
        "softwareConsultant": "Software Consultant",
        "it": "IT",
        "securityEngineer": "Security Engineer",
        "networkEngineer": "Network Engineer",
        "business": "Business",
        "businessConsultant": "Business Consultant",
        "security": "Security",
        "agent": "Agent",
        "employee": "Employee",
        "partTimeEmployee": "Part-time Employee",
        "waiter": "Waiter",
        "partTimeWaiter": "Part-time Waiter"
    },
    "JobName": {
        "IT0": "IT Intern",
        "IT1": "IT Analyst",
        "IT2": "IT Manager",
        "IT3": "Systems Administrator",
        "agent0": "Field Agent",
        "agent1": "Secret Agent",
        "agent2": "Special Operative",
        "business0": "Business Intern",
        "business1": "Business Analyst",
        "business2": "Business Manager",
        "business3": "Operations Manager",
        "business4": "Chief Financial Officer",
        "business5": "Chief Executive Officer",
        "businessConsult0": "Business Consultant",
        "businessConsult1": "Senior Business Consultant",
        "employee": "Employee",
        "employeePT": "Part-time Employee",
        "networkEng0": "Network Engineer",
        "networkEng1": "Network Administrator",
        "security0": "Security Guard",
        "security1": "Security Officer",
        "security2": "Security Supervisor",
        "security3": "Head of Security",
        "securityEng": "Security Engineer",
        "software0": "Software Engineering Intern",
        "software1": "Junior Software Engineer",
        "software2": "Senior Software Engineer",
        "software3": "Lead Software Developer",
        "software4": "Head of Software",
        "software5": "Head of Engineering",
        "software6": "Vice President of Technology",
        "software7": "Chief Technology Officer",
        "softwareConsult0": "Software Consultant",
        "softwareConsult1": "Senior Software Consultant",
        "waiter": "Waiter",
        "waiterPT": "Part-time Waiter",
    },
    "LocationName": {
        "AevumAeroCorp": "AeroCorp",
        "AevumBachmanAndAssociates": "Bachman & Associates",
        "AevumCasino": "Iker Molina Casino",
        "AevumClarkeIncorporated": "Clarke Incorporated",
        "AevumCrushFitnessGym": "Crush Fitness Gym",
        "AevumECorp": "ECorp",
        "AevumFulcrumTechnologies": "Fulcrum Technologies",
        "AevumGalacticCybersystems": "Galactic Cybersystems",
        "AevumNetLinkTechnologies": "NetLink Technologies",
        "AevumPolice": "Aevum Police Headquarters",
        "AevumRhoConstruction": "Rho Construction",
        "AevumSnapFitnessGym": "Snap Fitness Gym",
        "AevumSummitUniversity": "Summit University",
        "AevumWatchdogSecurity": "Watchdog Security",
        "ChongqingChurchOfTheMachineGod": "Church of the Machine God",
        "ChongqingKuaiGongInternational": "KuaiGong International",
        "ChongqingSolarisSpaceSystems": "Solaris Space Systems",
        "Hospital": "Hospital",
        "IshimaGlitch": "0x6C1",
        "IshimaNovaMedical": "Nova Medical",
        "IshimaOmegaSoftware": "Omega Software",
        "IshimaStormTechnologies": "Storm Technologies",
        "NewTokyoArcade": "Arcade",
        "NewTokyoDefComm": "DefComm",
        "NewTokyoGlobalPharmaceuticals": "Global Pharmaceuticals",
        "NewTokyoNoodleBar": "Noodle Bar",
        "NewTokyoVitaLife": "VitaLife",
        "Sector12AlphaEnterprises": "Alpha Enterprises",
        "Sector12BladeIndustries": "Blade Industries",
        "Sector12CIA": "Central Intelligence Agency",
        "Sector12CarmichaelSecurity": "Carmichael Security",
        "Sector12CityHall": "Sector-12 City Hall",
        "Sector12DeltaOne": "DeltaOne",
        "Sector12FoodNStuff": "FoodNStuff",
        "Sector12FourSigma": "Four Sigma",
        "Sector12IcarusMicrosystems": "Icarus Microsystems",
        "Sector12IronGym": "Iron Gym",
        "Sector12JoesGuns": "Joe's Guns",
        "Sector12MegaCorp": "MegaCorp",
        "Sector12NSA": "National Security Agency",
        "Sector12PowerhouseGym": "Powerhouse Gym",
        "Sector12RothmanUniversity": "Rothman University",
        "Sector12UniversalEnergy": "Universal Energy",
        "Slums": "The Slums",
        "TravelAgency": "Travel Agency",
        "Void": "The Void",
        "VolhavenCompuTek": "CompuTek",
        "VolhavenHeliosLabs": "Helios Labs",
        "VolhavenLexoCorp": "LexoCorp",
        "VolhavenMilleniumFitnessGym": "Millenium Fitness Gym",
        "VolhavenNWO": "NWO",
        "VolhavenOmniTekIncorporated": "OmniTek Incorporated",
        "VolhavenOmniaCybersystems": "Omnia Cybersystems",
        "VolhavenSysCoreSecurities": "SysCore Securities",
        "VolhavenZBInstituteOfTechnology": "ZB Institute of Technology",
        "WorldStockExchange": "World Stock Exchange",
    },
    "ToastVariant": {
        "ERROR": "error",
        "INFO": "info",
        "SUCCESS": "success",
        "WARNING": "warning",
    },
    "UniversityClassType": {
        "algorithms": "Algorithms",
        "computerScience": "Computer Science",
        "dataStructures": "Data Structures",
        "leadership": "Leadership",
        "management": "Management",
        "networks": "Networks",
    },
}